version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Optional: Use Browserless for development
  # This gives you instant browser management
  browserless:
    image: browserless/chrome:latest
    ports:
      - "3001:3000"
    environment:
      - CONCURRENT=10
      - QUEUED=20
      - PREBOOT_CHROME=true
      - TOKEN=your_secret_token
      - WORKSPACE_DIR=/tmp/workspace
      - CONNECTION_TIMEOUT=180000
      - MAX_PAYLOAD_SIZE=10485760
      - FUNCTION_ENABLE_INCOGNITO_MODE=true
      - ENABLE_CORS=true
      - CORS_ALLOW_ORIGINS=*
      - EXIT_ON_HEALTH_FAILURE=true
    volumes:
      - ./workspace:/tmp/workspace

  # Optional: Use DragonflyDB instead of Redis for 25x performance
  # dragonfly:
  #   image: docker.dragonflydb.io/dragonflydb/dragonfly
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - dragonfly_data:/data

volumes:
  redis_data:
  # dragonfly_data: