# Simplified Serverless config for Atlas Codex
service: atlas-codex

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  environment:
    NODE_ENV: production
    MASTER_API_KEY: ${env:MASTER_API_KEY, 'test-key-123'}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY, ''}
    QUEUE_URL: 
      Ref: JobQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
            - s3:*
            - sqs:*
            - execute-api:ManageConnections
            - execute-api:Invoke
          Resource: "*"

package:
  individually: true
  patterns:
    - '!packages/**'
    - '!node_modules/**'
    - '!.git/**'
    - '!.github/**'
    - '!*.md'
    - '!test/**'
    - '!tests/**'
    - '!.claude/**'
    - '!.serverless/**'
    - 'api/**'

functions:
  api:
    handler: api/lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
      - http:
          path: /
          method: ANY
          cors: true
    timeout: 30
    memorySize: 1024
    environment:
      WEBSOCKET_API_ENDPOINT:
        Fn::Sub: "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
  
  worker:
    handler: api/worker-enhanced.handler
    package:
      patterns:
        - '!**'
        - 'api/worker-enhanced.js'
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobQueue
              - Arn
          batchSize: 1
    timeout: 280  # Reduced to leave cleanup buffer
    memorySize: 3008  # Maximum memory for better performance
    environment:
      ARTIFACTS_BUCKET:
        Ref: ArtifactsBucket
      WEBSOCKET_API_ENDPOINT:
        Fn::Sub: "wss://${WebSocketApi}.execute-api.${AWS::Region}.amazonaws.com/dev"
  
  # WebSocket Connection Handler
  websocketConnect:
    handler: api/websocket.connect
    events:
      - websocket: $connect
    environment:
      CONNECTIONS_TABLE:
        Ref: ConnectionsTable
  
  # WebSocket Disconnect Handler  
  websocketDisconnect:
    handler: api/websocket.disconnect
    events:
      - websocket: $disconnect
    environment:
      CONNECTIONS_TABLE:
        Ref: ConnectionsTable
  
  # WebSocket Default Handler
  websocketDefault:
    handler: api/websocket.default
    events:
      - websocket: $default
    environment:
      CONNECTIONS_TABLE:
        Ref: ConnectionsTable

resources:
  Resources:
    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-jobs
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    JobQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-queue
        VisibilityTimeout: 360  # 6 minutes (longer than Lambda timeout)
        MessageRetentionPeriod: 86400  # 1 day
        ReceiveMessageWaitTimeSeconds: 20  # Long polling
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - JobDeadLetterQueue
              - Arn
          maxReceiveCount: 2  # Move to DLQ after 2 failed attempts
    
    # Dead Letter Queue for failed jobs
    JobDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-dlq
        MessageRetentionPeriod: 1209600  # 14 days
        VisibilityTimeout: 360
    
    ArtifactsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-artifacts-${sls:instanceId}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins: ["*"]
              AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT, POST]
    
    # WebSocket API
    WebSocketApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:service}-websocket
        ProtocolType: WEBSOCKET
        RouteSelectionExpression: "$request.body.action"
    
    # WebSocket Connections Table
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-connections
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
    
    # WebSocket Routes
    ConnectRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId:
          Ref: WebSocketApi
        RouteKey: $connect
        AuthorizationType: NONE
        Target:
          Fn::Sub: "integrations/${ConnectIntegration}"
    
    ConnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId:
          Ref: WebSocketApi
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketConnectLambdaFunction.Arn}/invocations"
    
    DisconnectRoute:
      Type: AWS::ApiGatewayV2::Route  
      Properties:
        ApiId:
          Ref: WebSocketApi
        RouteKey: $disconnect
        AuthorizationType: NONE
        Target:
          Fn::Sub: "integrations/${DisconnectIntegration}"
    
    DisconnectIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId:
          Ref: WebSocketApi
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketDisconnectLambdaFunction.Arn}/invocations"
    
    DefaultRoute:
      Type: AWS::ApiGatewayV2::Route
      Properties:
        ApiId:
          Ref: WebSocketApi
        RouteKey: $default
        AuthorizationType: NONE
        Target:
          Fn::Sub: "integrations/${DefaultIntegration}"
    
    DefaultIntegration:
      Type: AWS::ApiGatewayV2::Integration
      Properties:
        ApiId:
          Ref: WebSocketApi
        IntegrationType: AWS_PROXY
        IntegrationUri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketDefaultLambdaFunction.Arn}/invocations"
    
    # WebSocket Stage
    WebSocketStage:
      Type: AWS::ApiGatewayV2::Stage
      Properties:
        ApiId:
          Ref: WebSocketApi
        StageName: dev
        AutoDeploy: true
    
    # Lambda Permissions for WebSocket
    WebSocketConnectPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: WebsocketConnectLambdaFunction
        Principal: apigateway.amazonaws.com
        Action: lambda:InvokeFunction
    
    WebSocketDisconnectPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: WebsocketDisconnectLambdaFunction
        Principal: apigateway.amazonaws.com
        Action: lambda:InvokeFunction
    
    WebSocketDefaultPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: WebsocketDefaultLambdaFunction
        Principal: apigateway.amazonaws.com
        Action: lambda:InvokeFunction