version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3,sqs,lambda
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack_data:/var/lib/localstack
    
  api:
    build:
      context: ../../packages/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566
      - DYNAMODB_JOBS_TABLE=atlas-codex-jobs-dev
      - DYNAMODB_DIPS_TABLE=atlas-codex-dips-dev
      - DYNAMODB_EVIDENCE_TABLE=atlas-codex-evidence-dev
      - ARTIFACTS_BUCKET=atlas-codex-artifacts-dev
      - EVIDENCE_BUCKET=atlas-codex-evidence-dev
      - QUEUE_URL=http://localstack:4566/000000000000/atlas-codex-jobs-dev
    depends_on:
      - redis
      - localstack
    volumes:
      - ../../packages/api:/app
      - /app/node_modules
    
  worker:
    build:
      context: ../../packages/worker
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - S3_ENDPOINT=http://localstack:4566
      - SQS_ENDPOINT=http://localstack:4566
      - DYNAMODB_JOBS_TABLE=atlas-codex-jobs-dev
      - DYNAMODB_DIPS_TABLE=atlas-codex-dips-dev
      - DYNAMODB_EVIDENCE_TABLE=atlas-codex-evidence-dev
      - ARTIFACTS_BUCKET=atlas-codex-artifacts-dev
      - EVIDENCE_BUCKET=atlas-codex-evidence-dev
      - QUEUE_URL=http://localstack:4566/000000000000/atlas-codex-jobs-dev
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - localstack
    volumes:
      - ../../packages/worker:/app
      - /app/node_modules
    
  frontend:
    build:
      context: ../../packages/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ../../packages/frontend:/app
      - /app/node_modules

volumes:
  redis_data:
  localstack_data: